### ISSUE TITLE
Edit Entries

### ISSUE THREAD

**Issue by vmcampos** [vmcampos/vmcGas#2]
Add the ability for users to edit a past entry.

**Comment by vmcampos** [comment]
S'cuse me, @nolanlawson. Any chance you can take a quick look at my PouchDB problem? Can't seem to update a doc. Starts on Line 120 (Line 323 also relevant). Probably super-simple thing I'm missing. Cheers!

**Comment by nolanlawson** [comment]
Hi @vmcampos I checked out your code and edited a document, but it looks like I'm not getting any errors? Everything seems fine on my end. Could you provide more detail?

![screenshot 2015-10-04 15 00 59](https://cloud.githubusercontent.com/assets/283842/10269527/bebb3628-6aa8-11e5-9672-a40306fbba66.png)

**Comment by vmcampos** [comment]
Thanks a bunch @nolanlawson
But, notice how date has now become "undefined." 
And clicking Show Fillups doesn't show the updated fill up...

**Comment by nolanlawson** [comment]
OK I think I found the bug; it looks like you're not inserting the date in the document [here](https://github.com/vmcampos/vmcGas/blob/2b30a66cfc88d03bf4096ea86e4fcac03c673a14/index.html#L146).

**Comment by vmcampos** [comment]
Hmm. The date should be in _id, and I've tried _result._id_ (didn't work) and _d_ (didn't work either). Perhaps the the ISO date object has been fudged up?

**Comment by nolanlawson** [comment]
You can't directly store a Date object in PouchDB. Maybe that's what's happening?

**Comment by vmcampos** [comment]
True! That's why I converted to an ISO String (on line 83); as per the PouchDB example (great starting vid, by the way, Nolan!). 

I think using a date (as an ISO String) is the best way to create a unique _id for my doc; maybe there's a better way?

**Comment by nolanlawson** [comment]
Nope, `new Date().toISOString()` is a great way to do that; just be sure you don't try to store the Date itself or it will get converted for you..

**Comment by vmcampos** [comment]
@nolanlawson Seems to almost work now (was missing a date [had ISO date for Pouch, an a _pretty_ date for users] when updating). 
**But** now it updates **every** Doc with the same data!
Any idea why?

**Comment by vmcampos** [comment]
Looks like I got it working. 
Seemed to trying to use the wrong data types. 
Confirmed that with Number().
